### ISSUE TITLE
Uncaught TypeError: this.sortTemplate is not a function

### ISSUE THREAD

**Issue by am35a** [UziTech/context-menu-remove#3]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.25.0 x64
**Electron**: 1.7.11
**OS**: Unknown Windows version
**Thrown From**: [context-menu-remove](https://github.com/UziTech/context-menu-remove) package 0.2.0

### Stack Trace

Uncaught TypeError: this.sortTemplate is not a function

```
At C:\Users\Василий\.atom\packages\context-menu-remove\lib\contextMenu.js:100

TypeError: this.sortTemplate is not a function
    at ContextMenuManager.templateForEvent (/packages/context-menu-remove/lib/contextMenu.js:100:15)
    at ContextMenuManager.module.exports.ContextMenuManager.showForEvent (~/AppData/Local/atom/app-1.25.0/resources/app/src/context-menu-manager.js:189:33)
    at WindowEventHandler.handleDocumentContextmenu (~/AppData/Local/atom/app-1.25.0/resources/app/src/window-event-handler.js:257:44)
```

### Commands

```
```

### Non-Core Packages

```
atom-beautify 0.32.2 
autoclose-html 0.23.0 
autocomplete-paths 2.12.2 
busy-signal 1.4.3 
color-picker 2.2.5 
context-menu-remove 0.2.0 
copy-path 0.5.1 
double-tag 1.1.0 
emmet 2.4.3 
file-icons 2.1.15 
fold-lines 0.2.2 
highlight-selected 0.13.1 
indent-guide-improved 1.4.13 
intentions 1.1.5 
linter 2.2.0 
linter-ui-default 1

**Comment by UziTech** [comment]
Thanks for reporting. It should be fixed in v0.2.1
